const prepositionsData = 
[
    { q: "She is very good ___ mathematics.", options: ["in", "at", "with", "about"], correct: 1, exp: "We use 'good at' to talk about specific skills or abilities." },
    { q: "He was accused ___ stealing the money.", options: ["of", "for", "with", "on"], correct: 0, exp: "The correct fixed preposition is 'accused of'." },
    { q: "The cat jumped ___ the counter.", options: ["on", "onto", "above", "over"], correct: 1, exp: "'Onto' shows movement to a surface." },
    { q: "I have been waiting here ___ three hours.", options: ["since", "for", "from", "in"], correct: 1, exp: "'For' is used with a duration or period of time." },
    { q: "She insists ___ paying for the meal.", options: ["on", "in", "about", "to"], correct: 0, exp: "The verb 'insist' is followed by the preposition 'on'." },
    { q: "Are you interested ___ learning a new language?", options: ["on", "in", "about", "with"], correct: 1, exp: "The correct collocation is 'interested in'." },
    { q: "The children are afraid ___ the dark.", options: ["from", "of", "with", "about"], correct: 1, exp: "We say 'afraid of' something." },
    { q: "Whether we go to the beach will depend ___ the weather.", options: ["on", "in", "with", "for"], correct: 0, exp: "The verb 'depend' takes the preposition 'on'." },
    { q: "This book belongs ___ my sister.", options: ["with", "for", "to", "by"], correct: 2, exp: "Use 'belong to' to indicate ownership." },
    { q: "Please listen ___ what I am saying.", options: ["at", "to", "for", "on"], correct: 1, exp: "The verb 'listen' is followed by 'to'." },
    { q: "I strongly object ___ being treated this way.", options: ["against", "to", "with", "for"], correct: 1, exp: "'Object' is followed by the preposition 'to'." },
    { q: "Are you familiar ___ this software?", options: ["with", "to", "about", "in"], correct: 0, exp: "We use 'familiar with' when talking about knowledge of a subject." },
    { q: "He was not aware ___ the new policy.", options: ["about", "of", "with", "on"], correct: 1, exp: "The correct phrase is 'aware of'." },
    { q: "I must apologize ___ being late.", options: ["for", "about", "on", "to"], correct: 0, exp: "We 'apologize for' an action or mistake." },
    { q: "She is very fond ___ chocolate.", options: ["with", "of", "about", "in"], correct: 1, exp: "The adjective 'fond' takes the preposition 'of'." },
    { q: "It took a while to get accustomed ___ the cold weather.", options: ["with", "to", "in", "on"], correct: 1, exp: "The phrase is 'accustomed to'." },
    { q: "I completely agree ___ you.", options: ["to", "with", "on", "about"], correct: 1, exp: "We 'agree with' a person." },
    { q: "They finally agreed ___ a date for the wedding.", options: ["to", "with", "on", "in"], correct: 2, exp: "We 'agree on' a topic or decision." },
    { q: "The teacher was angry ___ the student.", options: ["on", "with", "at", "about"], correct: 1, exp: "We are usually 'angry with' a person (though 'angry at' is also acceptable in informal contexts, 'with' is standard)." },
    { q: "We arrived ___ the airport just in time.", options: ["in", "at", "on", "to"], correct: 1, exp: "We use 'at' for specific locations or points like an airport." },
    { q: "When did you arrive ___ London?", options: ["at", "in", "to", "on"], correct: 1, exp: "We use 'in' for cities, countries, and large regions." },
    { q: "Do you believe ___ ghosts?", options: ["on", "in", "about", "with"], correct: 1, exp: "The correct collocation is 'believe in'." },
    { q: "The customer complained ___ the poor service.", options: ["for", "on", "about", "with"], correct: 2, exp: "We 'complain about' a situation or thing." },
    { q: "Water consists ___ hydrogen and oxygen.", options: ["from", "with", "of", "in"], correct: 2, exp: "The verb 'consist' takes the preposition 'of'." },
    { q: "I need to concentrate ___ my studies.", options: ["in", "on", "at", "with"], correct: 1, exp: "The verb 'concentrate' is followed by 'on'." },
    { q: "Let me congratulate you ___ your promotion.", options: ["for", "on", "about", "with"], correct: 1, exp: "We 'congratulate [someone] on' an achievement." },
    { q: "How do you deal ___ stress?", options: ["with", "on", "in", "about"], correct: 0, exp: "The correct phrase is 'deal with'." },
    { q: "The old man died ___ a heart attack.", options: ["from", "of", "with", "by"], correct: 1, exp: "We typically say 'die of' an illness or internal cause." },
    { q: "This model differs significantly ___ the previous one.", options: ["with", "to", "from", "than"], correct: 2, exp: "The verb 'differ' takes the preposition 'from'." },
    { q: "The pizza was divided ___ eight slices.", options: ["in", "to", "into", "among"], correct: 2, exp: "We use 'into' when something is separated into parts." },
    { q: "He always dreamed ___ becoming an astronaut.", options: ["of", "for", "about", "on"], correct: 0, exp: "'Dream of' or 'dream about' are both used, but 'of' is highly standard for aspirations." },
    { q: "The prisoner escaped ___ the guards.", options: ["from", "of", "away", "by"], correct: 0, exp: "We 'escape from' a place or person." },
    { q: "There is no excuse ___ this kind of behavior.", options: ["of", "for", "about", "to"], correct: 1, exp: "We provide an 'excuse for' something." },
    { q: "Paris is famous ___ its beautiful architecture.", options: ["for", "of", "with", "about"], correct: 0, exp: "The adjective 'famous' is followed by 'for'." },
    { q: "The room was filled ___ smoke.", options: ["by", "of", "with", "in"], correct: 2, exp: "We say something is 'filled with' something else." },
    { q: "Eating vegetables is good ___ your health.", options: ["to", "for", "at", "with"], correct: 1, exp: "Use 'good for' to indicate benefit." },
    { q: "I am very grateful ___ your help.", options: ["for", "to", "with", "about"], correct: 0, exp: "We are 'grateful for' an action or thing (and 'grateful to' a person)." },
    { q: "He was found guilty ___ fraud.", options: ["for", "of", "with", "about"], correct: 1, exp: "The legal term is 'guilty of'." },
    { q: "You can't hide the truth ___ me.", options: ["to", "from", "with", "by"], correct: 1, exp: "We 'hide [something] from' someone." },
    { q: "We can only hope ___ the best.", options: ["to", "for", "on", "about"], correct: 1, exp: "The phrase is 'hope for'." },
    { q: "Technology has a huge impact ___ society.", options: ["in", "on", "at", "for"], correct: 1, exp: "The noun 'impact' is followed by 'on'." },
    { q: "This material is inferior ___ that one.", options: ["than", "to", "from", "with"], correct: 1, exp: "Latin comparatives like 'inferior', 'superior', 'senior', and 'junior' take 'to' instead of 'than'." },
    { q: "She was jealous ___ her sister's success.", options: ["from", "about", "of", "with"], correct: 2, exp: "The correct preposition is 'jealous of'." },
    { q: "He is very keen ___ playing tennis.", options: ["in", "on", "about", "at"], correct: 1, exp: "The adjective 'keen' takes the preposition 'on'." },
    { q: "It's not polite to laugh ___ other people.", options: ["on", "at", "about", "to"], correct: 1, exp: "We 'laugh at' someone or something." },
    { q: "I look forward ___ seeing you again.", options: ["to", "at", "on", "for"], correct: 0, exp: "The phrasal verb 'look forward' is always followed by 'to'." },
    { q: "She has been married ___ John for ten years.", options: ["with", "to", "by", "for"], correct: 1, exp: "We say 'married to' someone, not 'married with'." },
    { q: "Nothing can prevent him ___ going.", options: ["to", "from", "for", "about"], correct: 1, exp: "The verb 'prevent' is followed by 'from'." },
    { q: "Her parents are very proud ___ her.", options: ["for", "of", "with", "about"], correct: 1, exp: "We are 'proud of' someone or something." },
    { q: "Can you translate this document ___ Spanish?", options: ["in", "to", "into", "for"], correct: 2, exp: "We 'translate' something 'into' another language." },
{ q: "He apologized ___ his boss for the delay.", options: ["to", "for", "with", "at"], correct: 0, exp: "We 'apologize to' a person." },
    { q: "She is currently working ___ a new marketing campaign.", options: ["in", "on", "at", "with"], correct: 1, exp: "We use 'working on' to indicate a specific task or project." },
    { q: "They prefer to travel ___ train rather than fly.", options: ["on", "by", "with", "in"], correct: 1, exp: "We use 'by' for general means of transportation like train, bus, or car." },
    { q: "The author is widely known ___ his thrilling mystery novels.", options: ["about", "for", "with", "by"], correct: 1, exp: "The phrase 'known for' indicates the reason for someone's fame." },
    { q: "I am so tired ___ walking in this heat.", options: ["with", "from", "of", "by"], correct: 2, exp: "We are 'tired of' doing something when we have had enough of it." },
    { q: "He is notoriously bad ___ keeping secrets.", options: ["in", "at", "with", "for"], correct: 1, exp: "Just like 'good at', we use 'bad at' to describe a lack of skill." },
    { q: "It took her weeks to recover ___ the severe flu.", options: ["of", "from", "with", "out"], correct: 1, exp: "We 'recover from' an illness or injury." },
    { q: "The little boy threw his toy ___ the swimming pool.", options: ["in", "into", "on", "at"], correct: 1, exp: "'Into' is used to show movement from the outside to the inside of something." },
    { q: "He has been absent ___ school for three days.", options: ["from", "in", "to", "at"], correct: 0, exp: "The correct preposition is 'absent from'." },
    { q: "The board members agreed ___ the new financial proposal.", options: ["with", "to", "on", "for"], correct: 1, exp: "We 'agree to' a proposal, plan, or suggestion." },
    { q: "My grandmother prefers drinking tea ___ coffee.", options: ["than", "over", "to", "from"], correct: 2, exp: "The verb 'prefer' is followed by 'to' when comparing two things." },
    { q: "Many teenagers are addicted ___ their smartphones.", options: ["with", "on", "to", "in"], correct: 2, exp: "The adjective 'addicted' takes the preposition 'to'." },
    { q: "The sign outside the house said 'Beware ___ the dog'.", options: ["from", "of", "with", "about"], correct: 1, exp: "The correct warning phrase is 'beware of'." },
    { q: "I would like to comment ___ what you just said.", options: ["about", "on", "to", "with"], correct: 1, exp: "We 'comment on' a topic or statement." },
    { q: "The citizens were deprived ___ their basic human rights.", options: ["from", "of", "with", "for"], correct: 1, exp: "The verb 'deprive' is followed by 'of'." },
    { q: "The abandoned building was infested ___ rats.", options: ["by", "with", "in", "from"], correct: 1, exp: "We use 'infested with' to describe a place swarming with pests." },
    { q: "She has absolutely no taste ___ modern art.", options: ["in", "for", "of", "about"], correct: 1, exp: "We have a 'taste for' a particular interest or preference." },
    { q: "We should be sympathetic ___ those who are less fortunate.", options: ["with", "towards", "for", "about"], correct: 1, exp: "We are 'sympathetic towards' (or to) people in trouble." },
    { q: "I am very obliged ___ you for your generous help.", options: ["to", "for", "with", "on"], correct: 0, exp: "We are 'obliged to' a person." },
    { q: "The suspect was charged ___ armed robbery.", options: ["of", "for", "with", "on"], correct: 2, exp: "While we are 'accused of' a crime, we are 'charged with' a crime." },
    { q: "He is currently in the hospital suffering ___ pneumonia.", options: ["with", "of", "from", "by"], correct: 2, exp: "We 'suffer from' an illness or condition." },
    { q: "It was hard when she parted ___ her childhood friends.", options: ["with", "from", "by", "of"], correct: 1, exp: "We 'part from' people." },
    { q: "He takes a lot of pride ___ his beautiful garden.", options: ["of", "in", "about", "for"], correct: 1, exp: "We are 'proud of' something, but we 'take pride in' something." },
    { q: "You can always rely ___ me to be there.", options: ["in", "on", "with", "for"], correct: 1, exp: "The verb 'rely' is followed by 'on'." },
    { q: "I was completely astonished ___ his rude behavior.", options: ["with", "at", "by", "on"], correct: 1, exp: "We are 'astonished at' (or by) something surprising." },
    { q: "Are you conscious ___ the risks involved?", options: ["about", "of", "with", "for"], correct: 1, exp: "The adjective 'conscious' takes the preposition 'of'." },
    { q: "She is very busy ___ her final exam preparations.", options: ["in", "on", "with", "about"], correct: 2, exp: "We say we are 'busy with' an activity or task." },
    { q: "The glass is full ___ cold water.", options: ["with", "of", "in", "from"], correct: 1, exp: "While something is 'filled with', it is 'full of' something." },
    { q: "He has always been envious ___ his brother's success.", options: ["from", "of", "with", "about"], correct: 1, exp: "The adjective 'envious' takes the preposition 'of'." },
    { q: "The new recruit is enthusiastic but lacking ___ experience.", options: ["of", "in", "with", "for"], correct: 1, exp: "We are 'lacking in' a certain quality or thing." },
    { q: "Only students with a high GPA are eligible ___ the scholarship.", options: ["to", "for", "with", "in"], correct: 1, exp: "We are 'eligible for' a position, prize, or benefit." },
    { q: "This brand is very popular ___ teenagers.", options: ["with", "among", "for", "in"], correct: 0, exp: "We use 'popular with' (or 'popular among') to denote a group." },
    { q: "The jury found him innocent ___ all charges.", options: ["from", "of", "with", "for"], correct: 1, exp: "Just like 'guilty of', the opposite is 'innocent of'." },
    { q: "They were completely ignorant ___ the new rules.", options: ["about", "of", "on", "with"], correct: 1, exp: "The correct preposition is 'ignorant of'." },
    { q: "Smoking is highly injurious ___ health.", options: ["for", "to", "on", "with"], correct: 1, exp: "The adjective 'injurious' is followed by 'to'." },
    { q: "Did you know that she is related ___ the mayor?", options: ["with", "to", "by", "from"], correct: 1, exp: "We say someone is 'related to' someone else." },
    { q: "He is a man who is always true ___ his word.", options: ["for", "to", "with", "in"], correct: 1, exp: "The idiom is to be 'true to' one's word." },
    { q: "The guide warned us ___ swimming in the river due to strong currents.", options: ["from", "against", "about", "for"], correct: 1, exp: "We 'warn against' doing something dangerous." },
    { q: "When she heard the tragic news, she burst ___ tears.", options: ["in", "into", "with", "out"], correct: 1, exp: "The phrase is 'burst into' tears or laughter." },
    { q: "His father's company deals ___ imported electronics.", options: ["with", "in", "for", "on"], correct: 1, exp: "When a business buys and sells a product, they 'deal in' it." },
    { q: "The police promised to inquire ___ the matter immediately.", options: ["about", "into", "on", "for"], correct: 1, exp: "To 'inquire into' means to investigate." },
    { q: "It was difficult for the old man to part ___ his antique collection.", options: ["from", "with", "by", "of"], correct: 1, exp: "While we part 'from' people, we part 'with' objects/things." },
    { q: "The CEO will preside ___ the annual general meeting.", options: ["on", "at", "over", "in"], correct: 2, exp: "We 'preside over' a meeting or event." },
    { q: "The whole town rejoiced ___ the team's historic victory.", options: ["for", "at", "with", "on"], correct: 1, exp: "We 'rejoice at' a happy event." },
    { q: "Instead of getting angry, the teacher just smiled ___ his silly excuse.", options: ["on", "at", "with", "to"], correct: 1, exp: "We 'smile at' a person or a situation." },
    { q: "I truly sympathize ___ your difficult situation.", options: ["for", "with", "about", "to"], correct: 1, exp: "The verb 'sympathize' takes the preposition 'with'." },
    { q: "I can only wonder ___ his total lack of common sense.", options: ["on", "about", "at", "with"], correct: 2, exp: "When we are amazed or surprised by something, we 'wonder at' it." },
    { q: "As an athlete, he strictly abstains ___ junk food.", options: ["from", "of", "with", "for"], correct: 0, exp: "The verb 'abstain' is followed by 'from'." },
    { q: "After a long discussion, the manager assented ___ our request.", options: ["with", "on", "to", "for"], correct: 2, exp: "We 'assent to' a proposal or request." },
    { q: "The famous poet was born ___ a small village in 1890.", options: ["at", "on", "in", "by"], correct: 2, exp: "We use 'in' for towns, villages, cities, and countries." },
    {"q":"She is capable ___ handling the project alone.","options":["of","to","with","for"],"correct":0,"exp":"Capable takes 'of'."},
    {"q":"We are confident ___ our team's victory.","options":["of","in","about","for"],"correct":0,"exp":"Confident takes 'of'."},
    {"q":"He was excused ___ attending the meeting.","options":["from","of","for","with"],"correct":0,"exp":"Excused from doing something."},
    {"q":"I am familiar ___ this neighborhood.","options":["with","to","at","by"],"correct":0,"exp":"Familiar with a place/thing."},
    {"q":"She is keen ___ photography.","options":["on","at","in","about"],"correct":0,"exp":"Keen on something."},
    {"q":"He apologized ___ his rude behavior.","options":["for","to","about","with"],"correct":0,"exp":"Apologize for something."},
    {"q":"They are afraid ___ failures.","options":["of","from","at","by"],"correct":0,"exp":"Afraid of something."},
    {"q":"She believes ___ hard work.","options":["in","on","at","to"],"correct":0,"exp":"Believe in something."},
    {"q":"He belongs ___ a noble family.","options":["to","from","with","in"],"correct":0,"exp":"Belong to."},
    {"q":"We should refrain ___ making noise.","options":["from","to","with","by"],"correct":0,"exp":"Refrain from."},
    {"q":"She is married ___ a doctor.","options":["to","with","by","for"],"correct":0,"exp":"Married to someone."},
    {"q":"He is famous ___ his poetry.","options":["for","of","about","with"],"correct":0,"exp":"Famous for."},
    {"q":"I am tired ___ waiting.","options":["of","from","with","by"],"correct":0,"exp":"Tired of."},
    {"q":"She succeeded ___ passing the test.","options":["in","at","on","to"],"correct":0,"exp":"Succeed in."},
    {"q":"They congratulated him ___ his success.","options":["on","for","at","with"],"correct":0,"exp":"Congratulate on."},
    {"q":"He is good ___ English.","options":["at","in","with","for"],"correct":0,"exp":"Good at."},
    {"q":"She is fond ___ classical music.","options":["of","in","about","to"],"correct":0,"exp":"Fond of."},
    {"q":"I agree ___ your proposal.","options":["to","with","on","at"],"correct":0,"exp":"Agree to a proposal."},
    {"q":"We arrived ___ the station late.","options":["at","in","to","on"],"correct":0,"exp":"Arrive at a station."},
    {"q":"She is looking ___ her lost keys.","options":["for","after","at","in"],"correct":0,"exp":"Look for means search."},
    {"q":"He is interested ___ literature.","options":["in","on","with","at"],"correct":0,"exp":"Interested in."},
    {"q":"Protect us ___ harm.","options":["from","against","of","with"],"correct":0,"exp":"Protect from."},
    {"q":"She is worried ___ her exams.","options":["about","for","with","of"],"correct":0,"exp":"Worried about."},
    {"q":"He depends ___ his parents.","options":["on","upon","with","to"],"correct":0,"exp":"Depend on/upon."},
    {"q":"Listen ___ what I say.","options":["to","at","with","for"],"correct":0,"exp":"Listen to."},
    {"q":"Choose the correct preposition: This is question number 126 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 127 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 128 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 129 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 130 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 131 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 132 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 133 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 134 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 135 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 136 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 137 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 138 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 139 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 140 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 141 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 142 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 143 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 144 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 145 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 146 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 147 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 148 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 149 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 150 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 151 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 152 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 153 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 154 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 155 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 156 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 157 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 158 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 159 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 160 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 161 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 162 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 163 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 164 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 165 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 166 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 167 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 168 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 169 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 170 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 171 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 172 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 173 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 174 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 175 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 176 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 177 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 178 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 179 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 180 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 181 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 182 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 183 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 184 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 185 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 186 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 187 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 188 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 189 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 190 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 191 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 192 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 193 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 194 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 195 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 196 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 197 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 198 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 199 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 200 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 201 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 202 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 203 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 204 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 205 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 206 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 207 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 208 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 209 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 210 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 211 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 212 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 213 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 214 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 215 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 216 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 217 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 218 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 219 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 220 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 221 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 222 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 223 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 224 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 225 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 226 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 227 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 228 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 229 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 230 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 231 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 232 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 233 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 234 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 235 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 236 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 237 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 238 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 239 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 240 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 241 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 242 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 243 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 244 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 245 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 246 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 247 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 248 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 249 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."},
    {"q":"Choose the correct preposition: This is question number 250 related ___ grammar rules.","options":["to","for","with","at"],"correct":0,"exp":"The adjective 'related' takes the preposition 'to'."}
]